import { Contact } from '@/types/bdr';

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    company: 'Mitchell Architecture',
    role: 'Architect',
    relationshipType: 'Target',
    lastTouchDate: '2024-12-20',
    nextTouchDate: '2025-01-08',
    statusNotes: 'Met at AIA event. Interested in smart home tech for her luxury projects.',
    relationshipStrength: 3,
    tags: ['Luxury Residential', 'North Shore', 'High Potential'],
    board: 'prospect',
    stage: 'hot-stove',
    createdAt: '2024-11-15',
  },
  {
    id: '2',
    name: 'James Chen',
    company: 'Chen Builders',
    role: 'Builder',
    relationshipType: 'Active Partner',
    lastTouchDate: '2024-12-28',
    nextTouchDate: '2025-01-15',
    statusNotes: 'Currently working on 3 projects together. Great advocate.',
    relationshipStrength: 5,
    tags: ['Modern', 'High Volume', 'Advocate'],
    board: 'active',
    stage: 'strong-advocate',
    createdAt: '2024-06-01',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    company: 'ER Interior Design',
    role: 'Interior Designer',
    relationshipType: 'Target',
    lastTouchDate: '2024-11-10',
    nextTouchDate: '2024-12-15',
    statusNotes: 'Reached out via LinkedIn. No response yet.',
    relationshipStrength: 1,
    tags: ['Luxury Residential', 'Contemporary'],
    board: 'prospect',
    stage: 'first-contact',
    createdAt: '2024-11-08',
  },
  {
    id: '4',
    name: 'Michael Foster',
    company: 'Foster Landscape',
    role: 'Landscape Designer',
    relationshipType: 'Active Partner',
    lastTouchDate: '2024-10-15',
    nextTouchDate: '2024-11-20',
    statusNotes: 'Haven\'t connected in a while. Need to re-engage.',
    relationshipStrength: 3,
    tags: ['Outdoor Living', 'Smart Irrigation'],
    board: 'active',
    stage: 'under-engaged',
    createdAt: '2024-03-20',
  },
  {
    id: '5',
    name: 'Lisa Park',
    company: 'Park & Associates Realty',
    role: 'Real Estate Advisor',
    relationshipType: 'Influencer',
    lastTouchDate: '2024-12-22',
    nextTouchDate: '2025-01-10',
    statusNotes: 'Has referred 2 clients. Nurture this relationship.',
    relationshipStrength: 4,
    tags: ['UHNW Clients', 'North Shore'],
    board: 'active',
    stage: 'active-healthy',
    createdAt: '2024-08-15',
  },
  {
    id: '6',
    name: 'David Thompson',
    company: 'Thompson Design Studio',
    role: 'Architect',
    relationshipType: 'Target',
    lastTouchDate: null,
    nextTouchDate: null,
    statusNotes: 'Award-winning architect. Researching his recent projects.',
    relationshipStrength: 1,
    tags: ['Modern', 'High Profile', 'Award Winner'],
    board: 'prospect',
    stage: 'researching',
    createdAt: '2025-01-02',
  },
  {
    id: '7',
    name: 'Anna Williams',
    company: 'Williams Custom Homes',
    role: 'Builder',
    relationshipType: 'Target',
    lastTouchDate: '2024-12-18',
    nextTouchDate: '2025-01-05',
    statusNotes: 'Had great initial call. Scheduling site visit.',
    relationshipStrength: 3,
    tags: ['Custom Homes', 'High Potential'],
    board: 'prospect',
    stage: 'active-conversation',
    createdAt: '2024-12-10',
  },
  {
    id: '8',
    name: 'Robert Kim',
    company: 'Kim Architecture Group',
    role: 'Architect',
    relationshipType: 'Active Partner',
    lastTouchDate: '2025-01-02',
    nextTouchDate: '2025-01-20',
    statusNotes: 'Just started working together. Onboarding well.',
    relationshipStrength: 2,
    tags: ['New Partner', 'Modern'],
    board: 'active',
    stage: 'new-relationship',
    createdAt: '2024-12-28',
  },
];
